--!strict
return {
	{
		packageId = "rvtt.core.rules",
		version = "5.2.1-rvtt.1",
		dependencies = {},
		contentKinds = {
			"rule-packs",
			"rule-documents",
			"rule-search-index",
		},
		defaultProfiles = {
			"public",
			"release",
			"artifact",
		},
		rightsStatus = "built_in",
		licenseId = "CC-BY-4.0",
		attributionRequired = true,
		redistributable = true,
		publicBuildAllowed = true,
		clientExportAllowed = true,
	},
	{
		packageId = "rvtt.test.rules.2024.integrated.ko",
		version = "d3d574725e0ecdfd05cb69fa32cf66196e3a8ee4",
		dependencies = {
			"rvtt.core.rules",
		},
		contentKinds = {
			"rule-packs",
			"rule-documents",
			"rule-search-index",
			"character-options",
			"localization",
		},
		defaultProfiles = {
			"development",
			"test",
			"studio-acceptance",
		},
		sourceMode = "external_private_import",
		sourceBindingKey = "RVTT_PRIVATE_DND2024_KO_SOURCE",
		sourceRoot = "10-RULEBOOKS/integrated-2024",
		expectedContentCounts = {
			classes = 12,
			subclasses = 48,
			backgrounds = 16,
			species = 10,
			feats = 75,
			spells = 391,
		},
		rightsStatus = "developer_private",
		licenseId = "PRIVATE-USE-ONLY",
		attributionRequired = true,
		redistributable = false,
		publicBuildAllowed = false,
		clientExportAllowed = false,
		ownerOnly = true,
		failClosed = true,
	},
	{
		packageId = "rvtt.core.baseline",
		version = "2026.08.06",
		dependencies = {
			"rvtt.core.rules",
		},
		contentKinds = {
			"token-prefabs",
			"prop-prefabs",
			"tile-prefabs",
			"volume-prefabs",
			"materials",
			"vfx",
			"ui-assets",
		},
		defaultProfiles = {
			"development",
			"test",
			"studio-acceptance",
			"public",
			"release",
			"artifact",
		},
		rightsStatus = "built_in",
		licenseId = "RVTT-PROJECT",
		attributionRequired = false,
		redistributable = true,
		publicBuildAllowed = true,
		clientExportAllowed = true,
	},
}
